Page({
  data:{
    name:'CodeerWhy',
    age:18,
    students:[
      {id:110,name:'kobe',age:30},
      {id:111,name:'james',age:28},
      {id:112,name:'curry',age:32},
    ],
    countor:0
  },
  handleBtnClick(){
    this.setData({
      countor:this.data.countor+1
    })
  },
  handleSubtraction(){
    this.setData({
      countor:this.data.countor-1
    })
  }
})